game.setLocalization("title.atum.core.root", "§fThe Deserted");
game.setLocalization("title.atum.core.assassinassin", "§4The Assasin");
game.setLocalization("title.atum.core.pyramidscheme", "§eThe Tomb Raider");
game.setLocalization("title.atum.core.atumed", "§6§lIs Ozymandias");
game.setLocalization("title.atum.core.kingslayer", "§4§lThe Usurper");
game.setLocalization("title.atum.core.lawbringer", "§eThe Desert §4Peacekeeper");
game.setLocalization("title.atum.core.ajourney", "§8The Vagabound");
game.setLocalization("title.atum.core.pyramidscheme", "§eThe Tomb Raider");
game.setLocalization("title.atum.core.radyforaction", "§r§6§lThe Progidy  Of The Sun");
game.setLocalization("title.atum.core.thefullmuseum", "§6§lThe Desert Curator");