game.setLocalization("title.erebus.portal.root", "§aThe Erebus Researcher");
game.setLocalization("title.erebus.exploration.spray_can", "§aThe Insect Pest");
game.setLocalization("title.erebus.exploration.ant_amulet", "§6The Ant Queen");
game.setLocalization("title.erebus.exploration.entomology", "§cThe Insect Smasher");
game.setLocalization("title.erebus.exploration.water_striders", "§bThe Surfer");
game.setLocalization("title.erebus.exploration.rhino_beetle", "§bThe Rhino Poacher");
game.setLocalization("title.erebus.exploration.rhino_exo_set", "§7The Rhino Chitin");
game.setLocalization("title.erebus.exploration.titan_beetle", "§8§lThe Big Game Hunter");
game.setLocalization("title.erebus.exploration.traveller", "§a§lThe Erebus Researcher Extraordinaire");
game.setLocalization("title.erebus.exploration.kill_all", "§a§lThe Verminator");
game.setLocalization("title.erebus.exploration.exo_set", "§c§lOf Insect Blubber");