recipes.addShaped(<dungeontactics:wooden_cutlass>, [[<ore:plankWood>, null, null], [null, <ore:plankWood>, null], [null, null, <ore:stickWood>]]);
recipes.addShaped(<dungeontactics:bone_cutlass>, [[<ore:bone>, null, null], [null, <ore:bone>, null], [null, null, <ore:stickWood>]]);
recipes.addShaped(<dungeontactics:stone_cutlass>, [[<ore:cobblestone>, null, null], [null, <ore:cobblestone>, null], [null, null, <ore:stickWood>]]);
recipes.addShaped(<dungeontactics:iron_cutlass>, [[<ore:ingotIron>, null, null], [null, <ore:ingotIron>, null], [null, null, <ore:stickWood>]]);
recipes.addShaped(<dungeontactics:silver_cutlass>, [[<ore:ingotSilver>, null, null], [null, <ore:ingotSilver>, null], [null, null, <ore:stickWood>]]);
recipes.addShaped(<dungeontactics:golden_cutlass>, [[<ore:ingotGold>, null, null], [null, <ore:ingotGold>, null], [null, null, <ore:stickWood>]]);
recipes.addShaped(<dungeontactics:steel_cutlass>, [[<ore:ingotSteel>, null, null], [null, <ore:ingotSteel>, null], [null, null, <ore:stickWood>]]);
recipes.addShaped(<dungeontactics:diamond_cutlass>, [[<ore:gemDiamond>, null, null], [null, <ore:gemDiamond>, null], [null, null, <ore:stickWood>]]);
recipes.addShaped(<dungeontactics:mithril_cutlass>, [[<ore:ingotMithril>, null, null], [null, <ore:ingotMithril>, null], [null, null, <ore:stickWood>]]);