<inventorypets:loot_pet>.addTooltip("This pet is disabled due to reducing amount of loot gained when used with looting no point in reenabling.");
<inventorypets:double_chest_pet>.addTooltip("This pet is disabled due being able to dupe as well as not wanting to eat its food meaning you can lose items stored don't re-enable.");
<inventorypets:enchanting_table_pet>.addTooltip("This pet is disabled due to not recognising and working with modded enchants no point in reenabling.");
<inventorypets:chest_pet>.addTooltip("This pet is disabled due being able to dupe as well as not wanting to eat its food meaning you can lose items stored don't re-enable.");
<inventorypets:anvil_pet>.addTooltip("This pet is disabled due to being buggy and not using durabillity correctly and not functioning no point in reenabling.");
<inventorypets:grave_pet>.addTooltip("This Pet is disabled due to voiding items upon death and prevent graves from appearing don't re-enable it!");
<inventorypets:slime_pet>.addTooltip("This pet is disabled due to allowing players to be immortal for a cheap cost.");
<inventorypets:flying_saddle_pet>.addTooltip("This Pet is disabled due to breaking mob ai don't re-enable.");
<inventorypets:saddle_pet>.addTooltip("This Pet is disabled due to breaking mob ai don't re-enable.");
<inventorypets:wither_pet>.addTooltip(format.darkAqua("Be warned when using this pet with a weapon that has life steal enchantment you will receive damage in some instances. This can kill you!"));