<inventorypets:loot_pet>.addShiftTooltip("Easter Egg", "This pet is disabled due to reducing amount of loot gained when used with looting no point in reenabling");
<inventorypets:double_chest_pet>.addShiftTooltip("Easter Egg", "This pet is disabled due being able to dupe as well as not wanting to eat its food meaning you can lose items stored do not re-enable");
<inventorypets:enchanting_table_pet>.addShiftTooltip("Easter Egg", "This pet is disabled due to not recognising and working with modded enchants no point in reenabling");
<inventorypets:chest_pet>.addShiftTooltip("Easter Egg", "This pet is disabled due being able to dupe as well as not wanting to eat its food meaning you can lose items stored do not re-enable");
<inventorypets:anvil_pet>.addShiftTooltip("Easter Egg", "This pet is disabled due to being buggy and not using durabillity correctly and not functioning no point in reenabling");
<inventorypets:grave_pet>.addShiftTooltip("Easter Egg", "This Pet is disabled due to voiding items upon death and prevent graves from appearing do not re-enable it!");
<inventorypets:slime_pet>.addShiftTooltip("Only one that has a chance of being reenabled", "This pet is disabled due to allowing players to be immortal for a cheap cost");
<inventorypets:flying_saddle_pet>.addShiftTooltip("Easter Egg", "This Pet is disabled due to breaking mob ai do not re-enable");
<inventorypets:saddle_pet>.addShiftTooltip("Easter Egg", "This Pet is disabled due to breaking mob ai do not re-enable");
<inventorypets:wither_pet>.addShiftTooltip("This can kill you", "Be warned when using this pet with a weapon that has life steal enchantment you will receieve damage in some instances");